import React,{useState}from"react";
import type{BlueprintSelectionV1}from"../../contracts/blueprintSelection";
import{RangeEditor}from"./BlueprintPrimaryControls";

export function BlueprintCategoryEditor({selection,onCategory,onAdd,onRemove}:{selection:BlueprintSelectionV1;onCategory:(id:string,patch:Partial<BlueprintSelectionV1["categories"][number]>)=>void;onAdd:(label:string,explanation:string)=>void;onRemove:(id:string)=>void}){
  const[name,setName]=useState("");const[explanation,setExplanation]=useState("");const expert=selection.interfaceMode==="expert";
  const render=(category:BlueprintSelectionV1["categories"][number])=><details key={category.id} className="border p-3"><summary className="cursor-pointer flex justify-between gap-2"><strong>{category.label}</strong><span className="text-xs uppercase">{category.status} · {category.detail}</span></summary><p className="text-sm mt-3">{category.justification}</p><p className="text-xs mt-1">Purpose: {category.purpose}</p>{selection.interfaceMode!=="smart_auto"&&<div className="grid sm:grid-cols-2 gap-2 mt-3"><label className="text-xs">Status<select aria-label={`${category.label} status`} value={category.status} onChange={e=>onCategory(category.id,{status:e.target.value as typeof category.status})} className="block w-full border bg-transparent p-2 mt-1">{["recommended","optional","omitted","required"].map(value=><option key={value} value={value} disabled={category.status==="required"&&value==="omitted"}>{value}</option>)}</select></label><label className="text-xs">Detail<select aria-label={`${category.label} detail`} value={category.detail} onChange={e=>onCategory(category.id,{detail:e.target.value as typeof category.detail})} className="block w-full border bg-transparent p-2 mt-1">{["light","standard","rich","exhaustive"].map(value=><option key={value}>{value}</option>)}</select></label></div>}{expert&&<div className="mt-3 space-y-2"><RangeEditor label={`${category.label} entry range`} value={category.targetRange} onChange={value=>onCategory(category.id,{targetRange:value})}/><label className="text-xs block">Runtime role<select aria-label={`${category.label} runtime role`} value={category.likelyRuntimeRole} onChange={e=>onCategory(category.id,{likelyRuntimeRole:e.target.value as typeof category.likelyRuntimeRole})} className="block w-full border bg-transparent p-2 mt-1">{["evergreen","reference","dynamic","secret","ambient","state","mixed"].map(value=><option key={value}>{value}</option>)}</select></label></div>}<label className="text-xs mt-3 flex gap-2"><input type="checkbox" checked={category.userLocked} onChange={e=>onCategory(category.id,{userLocked:e.target.checked})}/>Keep my choice when recommendations refresh</label>{category.custom&&<button type="button" onClick={()=>onRemove(category.id)} className="btn-secondary mt-3">Remove custom category</button>}</details>;
  const active=selection.categories.filter(item=>item.status!=="omitted");const omitted=selection.categories.filter(item=>item.status==="omitted");
  return <section className="space-y-3"><h3 className="font-apparatus uppercase text-xs">Lore categories</h3><div className="space-y-2">{active.map(render)}</div><details className="border p-3"><summary className="cursor-pointer font-apparatus uppercase text-xs">Omitted categories ({omitted.length})</summary><div className="mt-3 space-y-2">{omitted.map(render)}{!omitted.length&&<p className="text-sm">No categories omitted.</p>}</div></details>{selection.interfaceMode!=="smart_auto"&&<fieldset className="border p-3"><legend className="font-apparatus uppercase text-xs">Add custom category</legend><label className="text-xs block">Category name<input aria-label="Custom category name" value={name} onChange={e=>setName(e.target.value)} className="block w-full border bg-transparent p-2 mt-1"/></label><label className="text-xs block mt-2">Why it matters<input aria-label="Custom category explanation" value={explanation} onChange={e=>setExplanation(e.target.value)} className="block w-full border bg-transparent p-2 mt-1"/></label><button type="button" disabled={!name.trim()} onClick={()=>{onAdd(name,explanation);setName("");setExplanation("");}} className="btn-secondary mt-3">Add custom category</button></fieldset>}</section>;
}
