import { expect, test } from "bun:test";
import { listPreparedProjectGraphs, previewBlueprint, ProjectGraphApiError } from "../../src/services/projectGraphService";
import { createBlueprintPlan } from "../../src/lib/blueprint/planner";
import { familyVisit } from "../fixtures/blueprintPremises";
test("returns prepared summaries and rejects credential-shaped responses",async()=>{const old=globalThis.fetch;try{globalThis.fetch=(async()=>new Response(JSON.stringify({projects:[{id:"p",name:"P",revision:1,status:"active",legacyDocumentId:"v"}]}),{status:200,headers:{"content-type":"application/json"}})) as any;expect((await listPreparedProjectGraphs())[0].legacyDocumentId).toBe("v");globalThis.fetch=(async()=>new Response(JSON.stringify({projects:[],apiKey:"x"}),{status:200})) as any;await expect(listPreparedProjectGraphs()).rejects.toThrow("credential");}finally{globalThis.fetch=old;}});
test("preserves coded revision conflicts",async()=>{const old=globalThis.fetch;try{globalThis.fetch=(async()=>new Response(JSON.stringify({error:{code:"revision_conflict",message:"Newer",actualRevision:3}}),{status:409})) as any;await expect(listPreparedProjectGraphs()).rejects.toMatchObject({code:"revision_conflict",actualRevision:3});}finally{globalThis.fetch=old;}});

test("posts only the Blueprint request, forwards cancellation, and parses the plan",async()=>{const old=globalThis.fetch;const controller=new AbortController();const input=familyVisit();const request={expectedRevision:input.graph.project.revision,context:input.context};const plan=createBlueprintPlan(input,{createdAt:"2026-09-10T12:00:00.000Z"});try{globalThis.fetch=(async(url,init)=>{expect(url).toBe("/api/projects/graph/project%3Ablueprint/blueprint-preview");expect(init?.signal).toBe(controller.signal);expect(JSON.parse(String(init?.body))).toEqual(request);return new Response(JSON.stringify({plan}),{status:200,headers:{"content-type":"application/json"}});}) as any;expect(await previewBlueprint(input.graph.project.id,request,controller.signal)).toEqual(plan);}finally{globalThis.fetch=old;}});

test("rejects unsafe Blueprint responses and preserves coded revision errors",async()=>{const old=globalThis.fetch;const input=familyVisit();const request={expectedRevision:input.graph.project.revision,context:input.context};try{globalThis.fetch=(async()=>new Response(JSON.stringify({plan:{apiKey:"unsafe"}}),{status:200})) as any;await expect(previewBlueprint(input.graph.project.id,request)).rejects.toThrow("credential");globalThis.fetch=(async()=>new Response(JSON.stringify({error:{code:"revision_conflict",message:"Newer",actualRevision:7}}),{status:409})) as any;await expect(previewBlueprint(input.graph.project.id,request)).rejects.toMatchObject({code:"revision_conflict",actualRevision:7});}finally{globalThis.fetch=old;}});
