import { expect, test } from "bun:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type { ProjectGraphV1 } from "../../src/contracts/projectGraph";
import { createProjectRepository, ProjectRepositoryError } from "../../server/projects/projectRepository";
import { compileProjectGraphArtifacts } from "../../src/lib/projectGraph/artifactCompiler";

function graph(id="project/one"):ProjectGraphV1{return {schema:"lorebible.project-graph/v1",project:{id,name:"World",version:"1",status:"active",targetPlatform:"lumiverse",mode:"graph_native",revision:1},authority:{sourceOrder:["user","approved_project","lumiverse_docs_technical","external_reference","generated"]},agency:{protectedSubject:"{{user}}",reserved:["actions","dialogue","thoughts","feelings","attraction","consent","decisions","relationships","abilities","backstory","next_voluntary_action"]},canon:[],entities:[{id:"e1",type:"character",name:"Mara",aliases:[],importance:"major",lifecycle:"active",factIds:[],relationshipIds:[],sourceEvidenceIds:[]}],relationships:[],knowledge:[],temporalSnapshots:[],ownership:[],sources:[],dependencies:[],artifacts:[],builds:[],validation:{status:"not_run",findings:[],lastRun:null},decisions:[],unresolved:[],extensions:{}}}
async function root(){return mkdtemp(join(tmpdir(),"lorebible-repo-"));}

test("creates, lists, and reloads through a fresh repository instance",async()=>{const dir=await root();const repo=createProjectRepository(dir);await repo.create(graph());expect((await repo.list())[0]).toMatchObject({id:"project/one",revision:1});expect((await createProjectRepository(dir).load("project/one"))?.project.name).toBe("World");});
test("serializes competing same-revision commands",async()=>{const dir=await root();const repo=createProjectRepository(dir);await repo.create(graph());const cmd=(name:string)=>repo.apply("project/one",{commandId:name,expectedRevision:1,issuedAt:"x",command:{type:"entity.rename",entityId:"e1",name}});const settled=await Promise.allSettled([cmd("A"),cmd("B")]);expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(settled.filter(x=>x.status==="rejected"&&x.reason.code==="revision_conflict")).toHaveLength(1);});
test("keeps a backup and explicitly restores it with a checksum precondition",async()=>{const dir=await root();const repo=createProjectRepository(dir);await repo.create(graph());await repo.apply("project/one",{commandId:"c",expectedRevision:1,issuedAt:"x",command:{type:"entity.rename",entityId:"e1",name:"Vale"}});const status=await repo.inspectRecovery("project/one");expect(status.backupValid).toBe(true);await expect(repo.restoreBackup("project/one","wrong")).rejects.toMatchObject({code:"recovery_conflict"});const restored=await repo.restoreBackup("project/one",status.primaryChecksum);expect(restored.project.revision).toBe(1);});
test("reports corruption without replacing the primary",async()=>{const dir=await root();const repo=createProjectRepository(dir);await repo.create(graph());const primary=join(dir,Buffer.from("project/one").toString("base64url"),"project.json");await writeFile(primary,"not-json");await expect(repo.load("project/one")).rejects.toMatchObject({code:"corrupt_primary"});expect(await readFile(primary,"utf8")).toBe("not-json");});
test("rejects credentials and traversal IDs stay encoded under root",async()=>{const dir=await root();const repo=createProjectRepository(dir);const unsafe=graph("../../escape");(unsafe.extensions as any).apiKey="secret";await expect(repo.create(unsafe)).rejects.toMatchObject({code:"credential_rejected"});const derived=join(dir,Buffer.from("../../escape").toString("base64url"),"project.json");expect(derived.startsWith(dir)).toBe(true);});

test("preserves the accepted edit and graph-native preview across a fresh repository instance",async()=>{const dir=await root();const repo=createProjectRepository(dir);await repo.create(graph("restart-proof"));const changed=await repo.apply("restart-proof",{commandId:"rename",expectedRevision:1,issuedAt:"2026-09-09T00:00:00Z",command:{type:"entity.rename",entityId:"e1",name:"Mara Vale"}});const before=compileProjectGraphArtifacts(changed.graph,()=>1_788_912_001);const reloaded=await createProjectRepository(dir).load("restart-proof");expect(reloaded).toEqual(changed.graph);const after=compileProjectGraphArtifacts(reloaded!,()=>1_788_912_001);expect(after).toEqual(before);expect(after.sourceRevision).toBe(2);});
