import React, { useEffect, useMemo, useRef, useState } from "react";
import { Check, Download, Eye, FlaskConical, Loader2, RotateCcw, Save, Square, Upload } from "lucide-react";
import type { PromptOverrideV1, PromptProfileV1 } from "../contracts/prompts";
import type { PromptRegistryEntry } from "../lib/prompts/registry";
import { cancelPromptTest, compilePromptPreview, createPromptProfile, listPromptCatalog, runPromptTest, updatePromptProfile, type PromptCompilePreview, type PromptTestResult } from "../services/promptsService";
import { parsePromptProfileImportV1, serializePromptProfileExportV1 } from "../lib/prompts/profileTransfer";
import type { BlueprintSelectionV1 } from "../contracts/blueprintSelection";
import type { ForgeSourceContextInput } from "../lib/prompts/forgeSourceContext";
import { buildForgeSourceContext } from "../lib/prompts/forgeSourceContext";
import type { ModelSelection } from "../contracts/generation";

interface ViewProps {
  features: readonly PromptRegistryEntry[]; profiles: readonly PromptProfileV1[]; selectedProfileId: string | null; selectedFeatureId: string;
  draftName: string; draftText: string; busy: boolean; error: string | null; status: string | null;
  onSelectProfile(id: string | null): void; onSelectFeature(id: string): void; onNameChange(value: string): void; onTextChange(value: string): void;
  onNew(): void; onSave(): void; onReset(): void;
  onImport?(): void; onExport?(): void;
  activeProfileId?: string | null; onActivateProfile?(id: string | null): void;
  projectOverrideText?: string; onProjectOverrideChange?(value: string | null): void;
  previewAvailable?: boolean; previewBusy?: boolean; preview?: PromptCompilePreview | null; onPreview?(): void;
  testAvailable?: boolean; testBusy?: boolean; testResult?: PromptTestResult | null; onTest?(): void; onCancelTest?(): void;
}
export function createPromptTestId(now = Date.now(), random = Math.random()): string {
  return `prompt-test-${Math.max(0, Math.floor(now)).toString(36)}-${Math.floor(Math.max(0, Math.min(0.999999999, random)) * 1_000_000_000).toString(36).padStart(6, "0")}`;
}
export function buildPromptComparison(feature: PromptRegistryEntry, profileText: string, projectText?: string) {
  const hasProject = Boolean(projectText?.trim());
  const hasProfile = profileText !== feature.defaultText;
  return {
    defaultText: feature.defaultText,
    profileText,
    projectText: projectText || "",
    effectiveText: hasProject ? projectText! : profileText,
    effectiveSource: hasProject ? "Project override" : hasProfile ? "Application profile" : "Shipped default",
  };
}
export function buildPromptOverrides(features: readonly PromptRegistryEntry[], values: Readonly<Record<string, string>>, profile: PromptProfileV1 | null) {
  return features.flatMap((feature) => {
    const text = values[feature.id];
    if (text === undefined || text === feature.defaultText) return [];
    const existing = profile?.overrides.find((item) => item.featureId === feature.id);
    return [{ featureId: feature.id, baseVersion: feature.defaultVersion, text, revision: existing && existing.text === text ? existing.revision : (existing?.revision || 0) + 1 }];
  });
}
export function PromptStudioView(props: ViewProps) {
  const feature = props.features.find((item) => item.id === props.selectedFeatureId) || props.features[0];
  return <div data-prompt-studio-scroll-root="true" className="min-h-0 flex-1 overflow-y-auto p-4 md:p-5">
    <div className="mb-4"><h2 className="font-apparatus text-sm uppercase tracking-widest">Creative Prompts</h2><p className="mt-1 text-[11px] text-[var(--graphite)]">Application profiles customize editable creative direction while protected schemas and safety rules remain server-owned.</p></div>
    <div className="mb-4 border border-[var(--gold)]/40 bg-[var(--gold)]/10 p-3 text-[11px] text-[var(--graphite)]"><strong>Project generation:</strong> Choose an active profile below. Forge freezes its effective instructions into the build, so retries and resumed checkpoints stay reproducible.</div>
    {props.error && <div className="mb-3 border border-red-800/40 p-2 text-xs text-red-700">{props.error}</div>}
    {props.status && <div className="mb-3 flex items-center gap-2 border border-emerald-800/30 p-2 text-xs text-emerald-800"><Check size={13}/>{props.status}</div>}
    <div className="grid gap-3 sm:grid-cols-[1fr_auto]">
      <label className="text-[10px] uppercase tracking-wider text-[var(--graphite)]">Application profile<select value={props.selectedProfileId || ""} onChange={(event) => props.onSelectProfile(event.target.value || null)} className="mt-1 w-full input-paper"><option value="">New profile</option>{props.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · r{profile.revision}</option>)}</select></label>
      <div className="flex flex-wrap gap-2 self-end"><button type="button" onClick={props.onNew} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider">New</button>{props.onImport && <button type="button" onClick={props.onImport} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2"><Upload size={13}/>Import profile JSON</button>}{props.onExport && <button type="button" onClick={props.onExport} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2"><Download size={13}/>Export profile JSON</button>}</div>
    </div>
    <label className="mt-3 block text-[10px] uppercase tracking-wider text-[var(--graphite)]">Profile name<input value={props.draftName} onChange={(event) => props.onNameChange(event.target.value)} className="mt-1 w-full input-paper" /></label>
    {props.onActivateProfile && <div className="mt-3 flex flex-wrap items-center gap-2 border border-[var(--ink-soft)] p-3"><button type="button" onClick={() => props.onActivateProfile!(props.selectedProfileId)} disabled={!props.selectedProfileId} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider">Use selected profile for this project</button><button type="button" onClick={() => props.onActivateProfile!(null)} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider">Use shipped defaults</button><span className="text-[10px] text-[var(--graphite)]">Active: {props.activeProfileId ? props.profiles.find((item) => item.id === props.activeProfileId)?.name ?? "Missing profile" : "Shipped defaults"}</span></div>}
    <div className="mt-5 grid gap-4 md:grid-cols-[190px_1fr]">
      <div className="space-y-1">{props.features.map((item) => <button key={item.id} type="button" onClick={() => props.onSelectFeature(item.id)} className={`w-full min-h-10 border-l-2 px-3 py-2 text-left text-xs ${item.id === feature?.id ? "border-[var(--rubric)] bg-[var(--vellum-raised)]" : "border-transparent hover:bg-[var(--vellum-raised)]"}`}>{item.label}<span className="block text-[9px] text-[var(--graphite)]">v{item.defaultVersion} · {item.id}</span></button>)}</div>
      {feature && <div className="min-w-0"><h3 className="font-apparatus text-sm">{feature.label}</h3><p className="mt-1 text-[11px] text-[var(--graphite)]">{feature.purpose}</p><p className="mt-2 text-[10px] text-[var(--graphite)]">Allowed literal variables: {feature.allowedVariables.join(", ")}</p>
        <textarea aria-label={`${feature.label} creative prompt`} value={props.draftText} onChange={(event) => props.onTextChange(event.target.value)} maxLength={24_000} className="mt-3 min-h-56 w-full input-paper font-mono-ui text-xs leading-relaxed" />
        {props.onProjectOverrideChange && <div className="mt-4 border border-[var(--gold)]/40 p-3"><h4 className="text-[10px] font-apparatus uppercase tracking-widest">This project override</h4><p className="mt-1 text-[11px] text-[var(--graphite)]">Optional final layer for this project only. It overrides the selected application profile for this feature.</p><textarea aria-label={`${feature.label} project override`} value={props.projectOverrideText ?? ""} onChange={(event) => props.onProjectOverrideChange!(event.target.value)} maxLength={24_000} placeholder="Leave blank to inherit the application profile." className="mt-2 min-h-32 w-full input-paper font-mono-ui text-xs leading-relaxed"/><button type="button" onClick={() => props.onProjectOverrideChange!(null)} disabled={!props.projectOverrideText} className="btn-secondary mt-2 min-h-10 px-4 text-[10px] uppercase tracking-wider">Clear project override</button></div>}
        <details className="mt-4 border border-[var(--ink-soft)] p-3"><summary className="cursor-pointer text-[10px] font-apparatus uppercase tracking-widest">Compare prompt layers</summary>{(() => { const comparison = buildPromptComparison(feature, props.draftText, props.projectOverrideText); return <div className="mt-3 space-y-3"><p className="text-[11px]"><strong>Effective source:</strong> {comparison.effectiveSource}</p>{[["Shipped default", comparison.defaultText], ["Application profile", comparison.profileText], ["Project override", comparison.projectText || "Not set"], ["Effective prompt", comparison.effectiveText]].map(([label, value]) => <div key={label}><h5 className="text-[9px] uppercase tracking-wider text-[var(--graphite)]">{label}</h5><pre className="mt-1 max-h-40 overflow-auto whitespace-pre-wrap border border-[var(--ink-soft)] bg-[var(--vellum-raised)] p-2 text-[10px]">{value}</pre></div>)}</div>; })()}</details>
        <div className="mt-3 border border-[var(--ink-soft)] p-3"><h4 className="text-[10px] font-apparatus uppercase tracking-widest">Protected requirements</h4><ul className="mt-2 list-disc space-y-1 pl-4 text-[11px] text-[var(--graphite)]">{feature.protectedRequirements.map((requirement) => <li key={requirement}>{requirement}</li>)}</ul></div>
        {props.onPreview && <div className="mt-4 border border-[var(--gold)]/40 bg-[var(--gold)]/5 p-3"><h4 className="text-[10px] font-apparatus uppercase tracking-widest">Compiled request preview</h4><p className="mt-1 text-[11px] text-[var(--graphite)]">This opt-in preview sends the current private project context to your local LoreBible server so it can compile the exact Forge request. It does not call the model, spend provider tokens, edit the manuscript, or alter a checkpoint.</p><button type="button" onClick={props.onPreview} disabled={!props.previewAvailable || props.previewBusy} className="btn-secondary mt-3 min-h-10 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2">{props.previewBusy ? <Loader2 size={13} className="animate-spin"/> : <Eye size={13}/>}Preview compiled request</button>{!props.previewAvailable && <p className="mt-2 text-[10px] text-[var(--graphite)]">Accept a Blueprint and enter a Spark before previewing a scheduled Forge specialist.</p>}{props.preview && <div className="mt-3 space-y-3"><p className="text-[10px] text-[var(--graphite)]">Job <strong>{props.preview.jobId}</strong> · schema <strong>{props.preview.schemaId}</strong><br/>Prompt hash: {props.preview.promptHash}<br/>Snapshot hash: {props.preview.snapshotHash}</p><div className="border border-emerald-800/30 p-2 text-[10px] text-emerald-800">No model call was made. The manuscript and Forge checkpoint were not changed.</div><details className="border border-[var(--ink-soft)] p-2"><summary className="cursor-pointer text-[10px] uppercase tracking-wider">System instruction</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap text-[10px]">{props.preview.systemInstruction}</pre></details><details className="border border-[var(--ink-soft)] p-2"><summary className="cursor-pointer text-[10px] uppercase tracking-wider">User request and private project context</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap text-[10px]">{props.preview.userPrompt}</pre></details></div>}</div>}
        {props.onTest && <div className="mt-4 border border-[var(--rubric)]/50 p-3"><h4 className="text-[10px] font-apparatus uppercase tracking-widest">Disposable model test</h4><p className="mt-1 text-[11px] text-[var(--graphite)]">Runs this feature once with the project’s active saved profile, current project override, accepted Blueprint, private context, and selected model. This can spend provider tokens. The validated candidate is not saved, applied, or added to Forge history.</p><div className="mt-3 flex flex-wrap gap-2">{props.testBusy ? <button type="button" onClick={props.onCancelTest} className="btn-secondary min-h-11 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2"><Square size={13}/>Cancel test</button> : <button type="button" onClick={props.onTest} disabled={!props.testAvailable} className="btn-primary min-h-11 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2"><FlaskConical size={13}/>Run disposable model test</button>}</div>{!props.testAvailable && <p className="mt-2 text-[10px] text-[var(--graphite)]">Accept a Blueprint, enter a Spark, and select a connection model before testing.</p>}{props.testResult && <div className="mt-3 space-y-2"><div className="border border-emerald-800/30 p-2 text-[10px] text-emerald-800">Disposable candidate · manuscript and checkpoint unchanged.</div><p className="text-[10px] text-[var(--graphite)]">{props.testResult.provenance.provider} · {props.testResult.provenance.modelReported || props.testResult.provenance.modelRequested}{props.testResult.provenance.usage ? ` · ${props.testResult.provenance.usage.inputTokens ?? "?"} input / ${props.testResult.provenance.usage.outputTokens ?? "?"} output tokens` : ""}</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap border border-[var(--ink-soft)] bg-[var(--vellum-raised)] p-2 text-[10px]">{JSON.stringify(props.testResult.candidate, null, 2)}</pre></div>}</div>}
        <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={props.onSave} disabled={props.busy} className="btn-primary min-h-10 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2">{props.busy ? <Loader2 size={13} className="animate-spin"/> : <Save size={13}/>}Save profile</button><button type="button" onClick={props.onReset} disabled={props.busy} className="btn-secondary min-h-10 px-4 text-[10px] uppercase tracking-wider flex items-center gap-2"><RotateCcw size={13}/>Use shipped default</button></div>
      </div>}
    </div>
  </div>;
}

export function PromptStudio(props: { activeProfileId?: string | null; onActiveProfileChange?(id: string | null): void; projectOverrides?: PromptOverrideV1[]; onProjectOverridesChange?(overrides: PromptOverrideV1[]): void; blueprintSelection?: BlueprintSelectionV1 | null; previewSource?: ForgeSourceContextInput; modelSelection?: ModelSelection | null } = {}) {
  const [features, setFeatures] = useState<PromptRegistryEntry[]>([]); const [profiles, setProfiles] = useState<PromptProfileV1[]>([]);
  const [profileId, setProfileId] = useState<string | null>(null); const [featureId, setFeatureId] = useState(""); const [name, setName] = useState("My creative profile");
  const [overrides, setOverrides] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState<string | null>(null);
  const [previewBusy, setPreviewBusy] = useState(false); const [preview, setPreview] = useState<PromptCompilePreview | null>(null);
  const [testBusy, setTestBusy] = useState(false); const [testResult, setTestResult] = useState<PromptTestResult | null>(null); const activeTest = useRef<{ id: string; controller: AbortController } | null>(null);
  const importInput = useRef<HTMLInputElement>(null);
  const profile = profiles.find((item) => item.id === profileId) || null; const feature = features.find((item) => item.id === featureId) || features[0];
  const text = feature ? overrides[feature.id] ?? feature.defaultText : "";
  const projectOverride=feature?props.projectOverrides?.find(item=>item.featureId===feature.id):undefined;
  const changeProjectOverride=(value:string|null)=>{if(!feature||!props.onProjectOverridesChange)return;const remaining=(props.projectOverrides??[]).filter(item=>item.featureId!==feature.id);if(value?.trim())remaining.push({featureId:feature.id,baseVersion:feature.defaultVersion,text:value,revision:(projectOverride?.revision??0)+1});props.onProjectOverridesChange(remaining);};
  useEffect(() => { void listPromptCatalog().then((catalog) => { setFeatures(catalog.features); setProfiles(catalog.profiles); setFeatureId(catalog.features[0]?.id || ""); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load Prompt Studio.")); }, []);
  useEffect(() => () => { const active = activeTest.current; if (active) { void cancelPromptTest(active.id).catch(() => undefined); active.controller.abort(); } }, []);
  const selectProfile = (id: string | null) => { const selected = profiles.find((item) => item.id === id); setProfileId(id); setName(selected?.name || "My creative profile"); setOverrides(Object.fromEntries(selected?.overrides.map((item) => [item.featureId, item.text]) || [])); setStatus(null); setError(null); };
  const draftOverrides = useMemo(() => buildPromptOverrides(features, overrides, profile), [features, overrides, profile]);
  const save = async () => { setBusy(true); setError(null); setStatus(null); try { const saved = profile ? await updatePromptProfile(profile.id, { name, overrides: draftOverrides }, profile.revision) : await createPromptProfile({ name, overrides: draftOverrides }); setProfiles((current) => current.some((item) => item.id === saved.id) ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved]); setProfileId(saved.id); setStatus("Profile saved. Activate it below when you want this project to use it."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save prompt profile."); } finally { setBusy(false); } };
  const importProfile = async (file: File) => { setBusy(true); setError(null); setStatus(null); try { const draft = parsePromptProfileImportV1(await file.text()); const saved = await createPromptProfile(draft); setProfiles((current) => [...current, saved]); selectProfile(saved.id); setName(saved.name); setOverrides(Object.fromEntries(saved.overrides.map((item) => [item.featureId, item.text]))); setStatus("Profile imported as a new application profile. It is not active until you choose to use it for this project."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to import prompt profile."); } finally { setBusy(false); if (importInput.current) importInput.current.value = ""; } };
  const exportProfile = () => { try { const content = serializePromptProfileExportV1({ name, overrides: draftOverrides }); const url = URL.createObjectURL(new Blob([content], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "prompt-profile"}.prompt-profile.json`; anchor.click(); URL.revokeObjectURL(url); setStatus("Prompt-only profile JSON exported. Project canon, credentials, and manuscript content were excluded."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to export prompt profile."); } };
  const previewCompiledRequest = async () => { if (!feature || !props.blueprintSelection || !props.previewSource) return; setPreviewBusy(true); setError(null); setPreview(null); try { const result = await compilePromptPreview({ featureId: feature.id, profileId: props.activeProfileId ?? null, projectOverrides: [...(props.projectOverrides ?? [])], selection: props.blueprintSelection, sourceContext: buildForgeSourceContext(props.previewSource) }); setPreview(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to compile prompt preview."); } finally { setPreviewBusy(false); } };
  const runDisposableTest = async () => { if (!feature || !props.blueprintSelection || !props.previewSource || !props.modelSelection?.profileId || !props.modelSelection.modelId) return; const id = createPromptTestId(); const controller = new AbortController(); activeTest.current = { id, controller }; setTestBusy(true); setTestResult(null); setError(null); setStatus(null); try { setTestResult(await runPromptTest({ testId: id, featureId: feature.id, profileId: props.activeProfileId ?? null, projectOverrides: [...(props.projectOverrides ?? [])], selection: props.blueprintSelection, sourceContext: buildForgeSourceContext(props.previewSource), modelSelection: props.modelSelection }, controller.signal)); setStatus("Disposable candidate ready. Nothing was saved or applied."); } catch (cause) { if (controller.signal.aborted) setStatus("Disposable prompt test cancelled. Nothing was saved or applied."); else setError(cause instanceof Error ? cause.message : "Unable to run disposable prompt test."); } finally { if (activeTest.current?.id === id) activeTest.current = null; setTestBusy(false); } };
  const cancelDisposableTest = async () => { const active = activeTest.current; if (!active) return; const remoteCancellation = cancelPromptTest(active.id); active.controller.abort(); try { await remoteCancellation; } catch { /* The test may already have completed. */ } };
  if (!features.length && !error) return <div className="flex min-h-48 items-center justify-center text-xs text-[var(--graphite)]"><Loader2 size={14} className="mr-2 animate-spin"/>Loading creative prompts…</div>;
  const contextReady = Boolean(props.blueprintSelection && props.previewSource?.sparkText.trim());
  const testAvailable = Boolean(contextReady && props.modelSelection?.profileId && props.modelSelection.modelId);
  return <><input ref={importInput} type="file" accept="application/json,.json" className="hidden" aria-label="Choose prompt profile JSON" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importProfile(file); }}/><PromptStudioView features={features} profiles={profiles} selectedProfileId={profileId} selectedFeatureId={feature?.id || ""} draftName={name} draftText={text} busy={busy} error={error} status={status} activeProfileId={props.activeProfileId} onActivateProfile={props.onActiveProfileChange} projectOverrideText={projectOverride?.text??""} onProjectOverrideChange={props.onProjectOverridesChange?changeProjectOverride:undefined} onImport={() => importInput.current?.click()} onExport={exportProfile} previewAvailable={contextReady} previewBusy={previewBusy} preview={preview} onPreview={() => void previewCompiledRequest()} testAvailable={testAvailable} testBusy={testBusy} testResult={testResult} onTest={() => void runDisposableTest()} onCancelTest={() => void cancelDisposableTest()} onSelectProfile={selectProfile} onSelectFeature={(id) => { setFeatureId(id); setPreview(null); setTestResult(null); }} onNameChange={setName} onTextChange={(value) => feature && setOverrides((current) => ({ ...current, [feature.id]: value }))} onNew={() => selectProfile(null)} onSave={() => void save()} onReset={() => feature && setOverrides((current) => { const next = { ...current }; delete next[feature.id]; return next; })} /></>;
}
