import { expect, test } from "bun:test";
import type { ProjectGraphV1 } from "../../src/contracts/projectGraph";
import { compileProjectGraphArtifacts } from "../../src/lib/projectGraph/artifactCompiler";

function graph():ProjectGraphV1{return {schema:"lorebible.project-graph/v1",project:{id:"p",name:"Harbor",version:"1",status:"active",targetPlatform:"lumiverse",mode:"graph_native",revision:4},authority:{sourceOrder:["user","approved_project","lumiverse_docs_technical","external_reference","generated"]},agency:{protectedSubject:"{{user}}",reserved:["actions","dialogue","thoughts","feelings","attraction","consent","decisions","relationships","abilities","backstory","next_voluntary_action"]},canon:[
{id:"f-desc",subjectId:"world",predicate:"premise",value:"A quiet harbor.",status:"canon",origin:"user",confidence:1,visibility:"public",temporalClass:"evergreen",sourceEvidenceIds:[]},
{id:"f-open",subjectId:"world",predicate:"opening.firstMessage",value:"The bell rings.",status:"canon",origin:"user",confidence:1,visibility:"public",temporalClass:"initial",sourceEvidenceIds:[]},
{id:"f-current",subjectId:"world",predicate:"status",value:"CURRENT_SENTINEL",status:"canon",origin:"user",confidence:1,visibility:"public",temporalClass:"current",sourceEvidenceIds:[]},
{id:"f-secret",subjectId:"mara",predicate:"secret",value:"SECRET_SENTINEL",status:"canon",origin:"user",confidence:1,visibility:"secret",temporalClass:"evergreen",sourceEvidenceIds:[]}],entities:[{id:"world",type:"concept",name:"Harbor",aliases:[],importance:"principal",lifecycle:"active",factIds:["f-desc","f-open","f-current"],relationshipIds:[],sourceEvidenceIds:[]},{id:"mara",type:"character",name:"Mara",aliases:["Harbormaster"],importance:"major",lifecycle:"active",factIds:["f-secret"],relationshipIds:[],sourceEvidenceIds:[]}],relationships:[],knowledge:[{id:"k",factId:"f-secret",entityId:"mara",state:"suspects",origin:"approved_project"}],temporalSnapshots:[],ownership:[{id:"o1",factId:"f-desc",owner:"character_description",rationale:"durable",origin:"user"},{id:"o2",factId:"f-open",owner:"first_message",rationale:"opening",origin:"user"}],sources:[],dependencies:[],artifacts:[],builds:[],validation:{status:"not_run",findings:[],lastRun:null},decisions:[],unresolved:[],extensions:{}}}

test("compiles only graph-owned fields and excludes current and secret facts from public card fields",()=>{const out=compileProjectGraphArtifacts(graph(),()=>123);expect(out.sourceRevision).toBe(4);expect(out.card.fields.description).toContain("A quiet harbor.");expect(out.card.fields.firstMessage).toBe("The bell rings.");expect(JSON.stringify(out.card.fields)).not.toContain("CURRENT_SENTINEL");expect(JSON.stringify(out.card.fields)).not.toContain("SECRET_SENTINEL");expect(out.card.fields.personality).toBe("");expect(out.findings.some(f=>f.code==="graph.card.personality_missing")).toBe(true);});
test("creates stable disabled secret lore and structurally parsed exports",()=>{const a=compileProjectGraphArtifacts(graph(),()=>123);const b=compileProjectGraphArtifacts(structuredClone(graph()),()=>123);expect(a.lore.entries.map(e=>e.nativeUid)).toEqual(b.lore.entries.map(e=>e.nativeUid));expect(a.lore.entries.find(e=>e.sourceFactIds.includes("f-secret"))?.activation.state).toBe("disabled");expect(a.validation).toEqual({graph:"pass",cardV3:"pass",nativeWorldBook:"pass"});expect((a.cardV3 as any).spec).toBe("chara_card_v3");});
