import type { CanonStatus, ForgeBuildRecordV1, ProjectGraphV1, TemporalClass, Visibility } from "../../contracts/projectGraph";
import { canonicalizeJson } from "./canonicalJson";
import { beginForgeBatch, cancelForgeBatch, completeForgeBatch, createForgeBuild, failForgeBatch, ForgeBuildError } from "./forgeBuilds";
import { parseProjectGraph } from "./validation";

export type ProjectGraphCommand =
  | { type:"entity.rename"; entityId:string; name:string }
  | { type:"canon.update"; factId:string; value:unknown; status?:CanonStatus; visibility?:Visibility; temporalClass?:TemporalClass }
  | { type:"forge.initialize"; buildId:string; inputFingerprint:string; executionMode:"continuous"|"step_by_step"|"single_request" }
  | { type:"forge.batch.begin"; buildId:string; bundleIndex:number; attemptId:string; provider:string; modelId:string; route:string; inputFingerprint:string; sourceRevision:number }
  | { type:"forge.batch.complete"; buildId:string; bundleIndex:number; attemptId:string; sections:Record<string,unknown>; inputFingerprint:string; sourceRevision:number }
  | { type:"forge.batch.fail"; buildId:string; bundleIndex:number; attemptId:string; code:string; message:string; inputFingerprint:string; sourceRevision:number }
  | { type:"forge.batch.cancel"; buildId:string; bundleIndex:number; attemptId:string; inputFingerprint:string; sourceRevision:number };
export interface ProjectGraphCommandEnvelope { commandId:string; expectedRevision:number; issuedAt:string; command:ProjectGraphCommand }
export interface ChangeImpact { targetId:string; path:string; classification:"automatic_structural_edit"|"proposed_semantic_edit"; reason:string }
export interface ProjectGraphChangeResult { graph:ProjectGraphV1; receipt:{schema:"lorebible.project-graph-change/v1";commandId:string;projectId:string;fromRevision:number;toRevision:number;changedIds:string[];automaticChanges:ChangeImpact[];proposedSemanticEdits:ChangeImpact[];unaffectedSummary:string[];appliedAt:string} }
export type CommandErrorCode="invalid_command"|"revision_conflict"|"missing_target"|"no_change"|"invalid_graph"|"credential_rejected";
export class ProjectGraphCommandError extends Error { constructor(message:string,public code:CommandErrorCode,public expectedRevision?:number,public actualRevision?:number){super(message);this.name="ProjectGraphCommandError";} }

function rejectCredentials(value:unknown,path="value"):void { if(!value||typeof value!=="object")return; for(const [k,v] of Object.entries(value)){if(/^(api[_-]?key|credential|access[_-]?token|secret[_-]?key)$/i.test(k))throw new ProjectGraphCommandError(`Credential-shaped field rejected at ${path}.${k}.`,"credential_rejected");rejectCredentials(v,`${path}.${k}`);} }
function proseImpacts(value:unknown,needle:string,path="",out:ChangeImpact[]=[]):ChangeImpact[]{ if(typeof value==="string"&&value.includes(needle))out.push({targetId:"project",path,classification:"proposed_semantic_edit",reason:`Text may reference the former entity name '${needle}'.`}); else if(value&&typeof value==="object")for(const [k,v] of Object.entries(value))proseImpacts(v,needle,path?`${path}.${k}`:k,out); return out; }
function forgeBuild(graph:ProjectGraphV1,id:string):ForgeBuildRecordV1{const build=graph.builds.find(item=>item.id===id);if(!build||build.kind!=="forge")throw new ProjectGraphCommandError("Forge build was not found.","missing_target");return build as ForgeBuildRecordV1;}
function forgeTransition<T>(work:()=>T):T{try{return work();}catch(error){if(error instanceof ForgeBuildError)throw new ProjectGraphCommandError(error.message,"invalid_command");throw error;}}
function verifyForgeTransition(build:ForgeBuildRecordV1,command:{inputFingerprint:string;sourceRevision:number},revision:number){if(build.inputFingerprint!==command.inputFingerprint||build.sourceRevision!==command.sourceRevision)throw new ProjectGraphCommandError("Forge build input or source revision is stale.","invalid_command");if(build.lastTransitionRevision!==revision)throw new ProjectGraphCommandError("Project changed outside this Forge build; start a new build from current canon.","invalid_command");}

export function applyProjectGraphCommand(input:ProjectGraphV1,envelope:ProjectGraphCommandEnvelope):ProjectGraphChangeResult{
  if(!envelope.commandId?.trim()||!Number.isSafeInteger(envelope.expectedRevision)||envelope.expectedRevision<1)throw new ProjectGraphCommandError("Invalid command envelope.","invalid_command");
  const revision=input.project.revision;
  if(!Number.isSafeInteger(revision)||revision!<1)throw new ProjectGraphCommandError("Graph revision is invalid.","invalid_graph");
  if(envelope.expectedRevision!==revision)throw new ProjectGraphCommandError("Project revision conflict.","revision_conflict",envelope.expectedRevision,revision);
  const graph=structuredClone(input); const automaticChanges:ChangeImpact[]=[]; let proposedSemanticEdits:ChangeImpact[]=[]; const changedIds:string[]=[];
  if(envelope.command.type==="entity.rename"){
    const command=envelope.command; const entity=graph.entities.find(x=>x.id===command.entityId); if(!entity)throw new ProjectGraphCommandError("Entity was not found.","missing_target");
    const name=command.name.trim(); if(!name)throw new ProjectGraphCommandError("Entity name is required.","invalid_command"); if(/\p{Cc}/u.test(name))throw new ProjectGraphCommandError("Entity name cannot contain control characters.","invalid_command"); if(name===entity.name)throw new ProjectGraphCommandError("Rename makes no change.","no_change");
    const old=entity.name; entity.name=name; if(old&&!entity.aliases.includes(old))entity.aliases.push(old); changedIds.push(entity.id); automaticChanges.push({targetId:entity.id,path:`entities.${entity.id}.name`,classification:"automatic_structural_edit",reason:"Stable entity display name changed and former name was retained as an alias."}); proposedSemanticEdits=proseImpacts(graph.extensions,old,"extensions");
  } else if(envelope.command.type==="canon.update"){
    const command=envelope.command; rejectCredentials(command.value); canonicalizeJson(command.value);
    const fact=graph.canon.find(x=>x.id===command.factId); if(!fact)throw new ProjectGraphCommandError("Canon fact was not found.","missing_target");
    const next={value:command.value,status:command.status??fact.status,visibility:command.visibility??fact.visibility,temporalClass:command.temporalClass??fact.temporalClass};
    if(canonicalizeJson({value:fact.value,status:fact.status,visibility:fact.visibility,temporalClass:fact.temporalClass})===canonicalizeJson(next))throw new ProjectGraphCommandError("Fact update makes no change.","no_change");
    Object.assign(fact,next); changedIds.push(fact.id); automaticChanges.push({targetId:fact.id,path:`canon.${fact.id}`,classification:"automatic_structural_edit",reason:"Explicit canon fact fields were updated without changing identity or provenance."});
  } else if(envelope.command.type==="forge.initialize"){
    const command=envelope.command;if(graph.builds.some(item=>item.id===command.buildId))throw new ProjectGraphCommandError("Build ID already exists.","invalid_command");
    const build=forgeTransition(()=>createForgeBuild({id:command.buildId,sourceRevision:revision,inputFingerprint:command.inputFingerprint,executionMode:command.executionMode,createdAt:envelope.issuedAt}));graph.builds.push(build);changedIds.push(build.id);automaticChanges.push({targetId:build.id,path:`builds.${build.id}`,classification:"automatic_structural_edit",reason:"Durable Forge build and six pending bundle records were initialized."});
  } else if(envelope.command.type==="forge.batch.begin"){
    const command=envelope.command;const index=graph.builds.findIndex(item=>item.id===command.buildId);const build=forgeBuild(graph,command.buildId);verifyForgeTransition(build,command,revision);const next=forgeTransition(()=>beginForgeBatch(build,{bundleIndex:command.bundleIndex,attemptId:command.attemptId,provider:command.provider,modelId:command.modelId,route:command.route,startedAt:envelope.issuedAt}));next.lastTransitionRevision=revision+1;graph.builds[index]=next;changedIds.push(build.id);automaticChanges.push({targetId:build.id,path:`builds.${build.id}.batches.${command.bundleIndex}`,classification:"automatic_structural_edit",reason:"Forge provider attempt began without altering completed bundle content."});
  } else if(envelope.command.type==="forge.batch.complete"){
    const command=envelope.command;rejectCredentials(command.sections);canonicalizeJson(command.sections);const index=graph.builds.findIndex(item=>item.id===command.buildId);const build=forgeBuild(graph,command.buildId);verifyForgeTransition(build,command,revision);const next=forgeTransition(()=>completeForgeBatch(build,{bundleIndex:command.bundleIndex,attemptId:command.attemptId,commandId:envelope.commandId,sections:command.sections,completedAt:envelope.issuedAt}));next.lastTransitionRevision=revision+1;graph.builds[index]=next;changedIds.push(build.id);automaticChanges.push({targetId:build.id,path:`builds.${build.id}.checkpoint`,classification:"automatic_structural_edit",reason:"Validated Forge bundle sections were accepted into the durable checkpoint."});
  } else if(envelope.command.type==="forge.batch.fail"){
    const command=envelope.command;const index=graph.builds.findIndex(item=>item.id===command.buildId);const build=forgeBuild(graph,command.buildId);verifyForgeTransition(build,command,revision);const next=forgeTransition(()=>failForgeBatch(build,{bundleIndex:command.bundleIndex,attemptId:command.attemptId,code:command.code,message:command.message,failedAt:envelope.issuedAt}));next.lastTransitionRevision=revision+1;graph.builds[index]=next;changedIds.push(build.id);automaticChanges.push({targetId:build.id,path:`builds.${build.id}.batches.${command.bundleIndex}`,classification:"automatic_structural_edit",reason:"Forge failure diagnostics were recorded while preserving accepted sections."});
  } else if(envelope.command.type==="forge.batch.cancel"){
    const command=envelope.command;const index=graph.builds.findIndex(item=>item.id===command.buildId);const build=forgeBuild(graph,command.buildId);verifyForgeTransition(build,command,revision);const next=forgeTransition(()=>cancelForgeBatch(build,{bundleIndex:command.bundleIndex,attemptId:command.attemptId,cancelledAt:envelope.issuedAt}));next.lastTransitionRevision=revision+1;graph.builds[index]=next;changedIds.push(build.id);automaticChanges.push({targetId:build.id,path:`builds.${build.id}.batches.${command.bundleIndex}`,classification:"automatic_structural_edit",reason:"Forge cancellation was recorded without discarding accepted sections."});
  } else throw new ProjectGraphCommandError("Unsupported command.","invalid_command");
  graph.project.revision=revision+1; const parsed=parseProjectGraph(graph); if("issues" in parsed)throw new ProjectGraphCommandError("Command produced an invalid graph.","invalid_graph");
  return {graph,receipt:{schema:"lorebible.project-graph-change/v1",commandId:envelope.commandId,projectId:graph.project.id,fromRevision:revision,toRevision:revision+1,changedIds,automaticChanges,proposedSemanticEdits,unaffectedSummary:["Stable IDs and unrelated records were preserved."],appliedAt:envelope.issuedAt}};
}
