import type{EntityType,ForgeCategoryRecordKind,ForgeCategoryRecordV1,ForgeSpecialistProjectionV1}from"../../contracts/projectGraph";

const CATEGORY:Record<string,string>={core:"world",user:"user",worldPhysics:"world_rule",status:"state",locations:"location",factions:"faction",npcs:"character",relationshipWeb:"relationship",knowledgeMap:"knowledge",items:"item",secrets:"secret",conflict:"conflict",pressureProtocol:"pressure",history:"history",aesthetic:"aesthetic",naming:"naming",pressures:"pressure",proceduralRolls:"event",opening:"opening",expansionNotes:"project_note",antiGravity:"quality_rule",buildNotes:"project_note"};
const ENTITY=new Set(["locations","factions","npcs","items"]);const TEMPORAL=new Set(["history","pressures"]);const COLLECTIONS=new Set(["locations","factions","npcs","relationshipWeb","knowledgeMap","items","secrets","history","pressures","proceduralRolls"]);
const ENTITY_TYPE:Record<string,EntityType>={locations:"location",factions:"faction",npcs:"character",items:"item"};
function fields(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return{} as Record<string,unknown>;const record=value as Record<string,unknown>;return record.fields&&typeof record.fields==="object"&&!Array.isArray(record.fields)?record.fields as Record<string,unknown>:record;}
function text(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null;}
function semanticName(sectionKey:string,payload:unknown){const value=fields(payload);if(sectionKey==="relationshipWeb"){const source=text(value.source);const target=text(value.target);if(source&&target)return`${source} ↔ ${target}`;}return text(value.name)??text(value.title)??text(value.event)??text(value.truth)??text(value.label);}
function kind(sectionKey:string):ForgeCategoryRecordKind{return ENTITY.has(sectionKey)?"entity":sectionKey==="relationshipWeb"?"relationship":sectionKey==="knowledgeMap"?"knowledge":TEMPORAL.has(sectionKey)?"temporal_fact":"section";}
function projection(sectionKey:string,payload:unknown):ForgeSpecialistProjectionV1|undefined{const value=fields(payload);if(ENTITY.has(sectionKey)){const tier=value.castTier==="principal"||value.castTier==="roster"?value.castTier:"unclassified";return{kind:"entity",entityType:ENTITY_TYPE[sectionKey]??"other",name:text(value.name),castTier:tier,independentGoal:text(value.wants)??text(value.independentWant),independentActivity:text(value.independentActivity)};}if(sectionKey==="relationshipWeb")return{kind:"relationship",sourceName:text(value.source),targetName:text(value.target),publicDynamic:text(value.bond),tension:text(value.pressure),direction:text(value.relation)};if(sectionKey==="knowledgeMap")return{kind:"knowledge",truth:text(value.truth),knownBy:text(value.knows),suspectedBy:text(value.suspects),surfacesWhen:text(value.surfacesWhen)};if(sectionKey==="history")return{kind:"temporal_fact",temporalClass:"historical",label:text(value.event),timing:text(value.era),consequence:text(value.consequence)};if(sectionKey==="pressures")return{kind:"temporal_fact",temporalClass:"current",label:text(value.name),timing:text(value.clock),consequence:text(value.force)};return undefined;}
function digest(value:string){let hash=14695981039346656037n;const mask=0xffffffffffffffffn;for(let index=0;index<value.length;index++){hash^=BigInt(value.charCodeAt(index));hash=(hash*1099511628211n)&mask;}return hash.toString(16).padStart(16,"0");}
function id(buildId:string,bundleIndex:number,sectionKey:string,sourceEntryId:string|null,ordinal:number){return`forge-category:${digest(JSON.stringify([buildId,bundleIndex,sectionKey,sourceEntryId,ordinal]))}`;}
function record(buildId:string,bundleIndex:number,sectionKey:string,payload:unknown,ordinal:number,recordKind:ForgeCategoryRecordKind):ForgeCategoryRecordV1{const value=structuredClone(payload);const raw=payload&&typeof payload==="object"&&!Array.isArray(payload)?(payload as Record<string,unknown>).id:null;const sourceEntryId=text(raw);const specialist=projection(sectionKey,payload);return{id:id(buildId,bundleIndex,sectionKey,sourceEntryId,ordinal),schema:"lorebible.forge-category-record/v1",buildId,bundleIndex,sectionKey,categoryId:CATEGORY[sectionKey]??"custom",recordKind,ordinal,sourceEntryId,semanticName:semanticName(sectionKey,payload),status:"proposed",origin:"generated",payload:value,...(specialist?{projection:specialist}:{})};}

export function projectForgeSections(buildId:string,bundleIndex:number,sections:Record<string,unknown>):ForgeCategoryRecordV1[]{const output:ForgeCategoryRecordV1[]=[];for(const[sectionKey,value]of Object.entries(sections)){if(Array.isArray(value)){if(value.length===0)output.push(record(buildId,bundleIndex,sectionKey,[],0,"empty_collection"));else value.forEach((item,index)=>output.push(record(buildId,bundleIndex,sectionKey,item,index,kind(sectionKey))));}else output.push(record(buildId,bundleIndex,sectionKey,value,0,kind(sectionKey)));}return output;}
export function deriveForgeSectionsFromCategoryRecords(records:readonly ForgeCategoryRecordV1[]):Record<string,unknown>{const output:Record<string,unknown>={};const ordered=[...records].sort((a,b)=>a.bundleIndex-b.bundleIndex||a.ordinal-b.ordinal);for(const item of ordered){if(item.recordKind==="empty_collection"){output[item.sectionKey]=[];continue;}if(COLLECTIONS.has(item.sectionKey)){const collection=Array.isArray(output[item.sectionKey])?output[item.sectionKey] as unknown[]:[];collection.push(structuredClone(item.payload));output[item.sectionKey]=collection;}else output[item.sectionKey]=structuredClone(item.payload);}return output;}
