import { expect, test } from "bun:test";
import express from "express";
import { mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type { ProjectGraphV1 } from "../../src/contracts/projectGraph";
import { createProjectRepository } from "../../server/projects/projectRepository";
import { registerProjectRoutes } from "../../server/routes/projects";
import { createDraftScenarioDocument, DEFAULT_CANON, DEFAULT_PHYSICS } from "../../src/lib/scenarioDraft";
import { createSavedProjectV2 } from "../../src/lib/projectPersistence";

function graph():ProjectGraphV1{return {schema:"lorebible.project-graph/v1",project:{id:"route-project",name:"World",version:"1",status:"active",targetPlatform:"lumiverse",mode:"graph_native",revision:1},authority:{sourceOrder:["user","approved_project","lumiverse_docs_technical","external_reference","generated"]},agency:{protectedSubject:"{{user}}",reserved:["actions","dialogue","thoughts","feelings","attraction","consent","decisions","relationships","abilities","backstory","next_voluntary_action"]},canon:[],entities:[{id:"e",type:"character",name:"Mara",aliases:[],importance:"major",lifecycle:"active",factIds:[],relationshipIds:[],sourceEvidenceIds:[]}],relationships:[],knowledge:[],temporalSnapshots:[],ownership:[],sources:[],dependencies:[],artifacts:[],builds:[],validation:{status:"not_run",findings:[],lastRun:null},decisions:[],unresolved:[],extensions:{}}}
async function harness(){const repo=createProjectRepository(await mkdtemp(join(tmpdir(),"lb-route-")));const app=express();app.use(express.json());registerProjectRoutes(app,{repository:repo});const server=app.listen(0);await new Promise(r=>server.once("listening",r));const port=(server.address() as any).port;return{repo,url:`http://127.0.0.1:${port}`,close:()=>server.close()};}
test("creates, lists, loads, and applies commands without exposing paths",async()=>{const h=await harness();try{expect((await fetch(h.url+"/api/projects/graph",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(graph())})).status).toBe(201);const list=await(await fetch(h.url+"/api/projects/graph")).json() as any;expect(list.projects[0]).toMatchObject({id:"route-project",revision:1});expect(JSON.stringify(list)).not.toContain("AppData");const res=await fetch(h.url+"/api/projects/graph/route-project/commands",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandId:"c",expectedRevision:1,issuedAt:"x",command:{type:"entity.rename",entityId:"e",name:"Vale"}})});expect(res.status).toBe(200);expect((await res.json() as any).graph.project.revision).toBe(2);}finally{h.close();}});
test("maps revision conflict and malformed input safely",async()=>{const h=await harness();try{await h.repo.create(graph());const conflict=await fetch(h.url+"/api/projects/graph/route-project/commands",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandId:"c",expectedRevision:9,issuedAt:"x",command:{type:"entity.rename",entityId:"e",name:"Vale"}})});expect(conflict.status).toBe(409);expect(await conflict.json()).toMatchObject({error:{code:"revision_conflict"}});const bad=await fetch(h.url+"/api/projects/graph",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});expect(bad.status).toBe(400);}finally{h.close();}});

test("migrates one V2 project idempotently and compiles the stored revision",async()=>{const h=await harness();try{const d=createDraftScenarioDocument({sparkText:"A harbor.",parse:null,canon:DEFAULT_CANON,physics:DEFAULT_PHYSICS,title:"Harbor"});d.id="legacy-1";d.npcs=[{id:"m",fields:{name:"Mara",role:"Keeper"},keys:["Mara"],permanence:"C",locked:true}];d.opening.firstMessage="The bell rings.";const saved=createSavedProjectV2({document:d,workflow:{stage:"5",sparkParse:d.parse,canon:d.canon,physics:d.physics,takes:[],selectedTakeId:null},generation:{settings:{quality:"Deep Craft",divergenceMode:"Exploratory",authorFlavor:{mode:"Off",strength:"Sprinkle",autoBehavior:"Compatible"},modelSelection:{profileId:null,modelId:null}},modelSelection:{profileId:null,modelId:null},provenance:[]},savedAt:"2026-01-01T00:00:00Z"});const first=await fetch(h.url+"/api/projects/graph/migrate-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(saved)});expect(first.status).toBe(201);const body=await first.json() as any;const second=await fetch(h.url+"/api/projects/graph/migrate-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(saved)});expect(second.status).toBe(200);expect((await second.json() as any).status).toBe("already_prepared");const preview=await(await fetch(`${h.url}/api/projects/graph/${encodeURIComponent(body.graph.project.id)}/compile-preview`)).json() as any;expect(preview.sourceRevision).toBe(1);expect(preview.card.fields.name).toBe("Harbor");expect(preview.validation.nativeWorldBook).toBe("pass");}finally{h.close();}});
